-- SECTION 3: Database, Warehouse, and Schema Setup
-- (Template database COCO_SDLC_HOL_99 — cloned for all attendees in Section 10)
-- ============================================================
USE ROLE ATTENDEE_ROLE;

CREATE DATABASE IF NOT EXISTS COCO_SDLC_HOL_99
    COMMENT = 'evolv Payment Analytics hands-on lab environment with sample payment data and reference tables';

USE DATABASE COCO_SDLC_HOL_99;

CREATE SCHEMA IF NOT EXISTS RAW
    COMMENT = 'Raw normalized OLTP-style tables with legacy naming conventions';
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS MARTS;
CREATE SCHEMA IF NOT EXISTS PUBLIC;

-- Grant schema-level privileges to ATTENDEE_ROLE (requires ACCOUNTADMIN)
USE ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON DATABASE COCO_SDLC_HOL_99 TO ROLE ATTENDEE_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA COCO_SDLC_HOL_99.RAW TO ROLE ATTENDEE_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA COCO_SDLC_HOL_99.STAGING TO ROLE ATTENDEE_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA COCO_SDLC_HOL_99.INTERMEDIATE TO ROLE ATTENDEE_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA COCO_SDLC_HOL_99.MARTS TO ROLE ATTENDEE_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA COCO_SDLC_HOL_99.PUBLIC TO ROLE ATTENDEE_ROLE;
USE ROLE ATTENDEE_ROLE;

