-- SECTION 9: Final Grants
-- ============================================================
GRANT USAGE ON AGENT COCO_SDLC_HOL_99.MARTS.PAYMENT_ANALYTICS_AGENT TO ROLE ATTENDEE_ROLE;
GRANT OWNERSHIP ON AGENT COCO_SDLC_HOL_99.MARTS.PAYMENT_ANALYTICS_AGENT TO ROLE ATTENDEE_ROLE COPY CURRENT GRANTS;
GRANT USAGE ON DBT PROJECT COCO_SDLC_HOL_99.MARTS.EVOLV_PAYMENT_ANALYTICS TO ROLE ATTENDEE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA COCO_SDLC_HOL_99.MARTS TO ROLE ATTENDEE_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA COCO_SDLC_HOL_99.MARTS TO ROLE ATTENDEE_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA COCO_SDLC_HOL_99.STAGING TO ROLE ATTENDEE_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA COCO_SDLC_HOL_99.INTERMEDIATE TO ROLE ATTENDEE_ROLE;


